qwen3_asr_src = [
    meson.current_source_dir() / 'qwen3_asr_causallm.cpp',
    meson.current_source_dir() / 'qwen3_asr_subsampler.cpp',
    meson.current_source_dir() / 'audio_preprocessor.cpp',
]

qwen3_asr_inc = include_directories('.')

causallm_src += qwen3_asr_src
causallm_inc += qwen3_asr_inc
