# Cross compilation configuration for Raspberry Pi 5 (Cortex-A76, ARMv8.2-A, Linux aarch64)

[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-ar'
strip = 'aarch64-linux-gnu-strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'armv8.2-a'
endian = 'little'

[built-in options]
werror = false
c_args = ['-O3', '-mcpu=cortex-a76', '-march=armv8.2-a+fp16+dotprod', '-DENABLE_FP16=1', '-DUSE__FP16=1', '-I/hdd/workspace/temp/qwen3-asr/nntrainer/builddir/openblas/include']
cpp_args = ['-O3', '-mcpu=cortex-a76', '-march=armv8.2-a+fp16+dotprod', '-DENABLE_FP16=1', '-DUSE__FP16=1', '-std=c++20', '-I/hdd/workspace/temp/qwen3-asr/nntrainer/builddir/openblas/include']
c_link_args = ['-L/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu/openblas-pthread', '-L/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-Wl,-rpath-link,/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-lopenblas', '-lgfortran']
cpp_link_args = ['-L/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu/openblas-pthread', '-L/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-Wl,-rpath-link,/hdd/workspace/temp/qwen3-asr/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-lopenblas', '-lgfortran']

[project options]
platform = 'none'
arm-arch = 'armv8.2-a'
enable-fp16 = true
enable-app = true
install-app = true
enable-test = false
enable-logging = true
enable-tflite-backbone = false
enable-nnstreamer-backbone = false
enable-tflite-interpreter = false
enable-mmap = true
mmap-read = true
quick_ai-tokenizer = true
