# SPDX-License-Identifier: Apache-2.0
##
# Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
#
# @file   rpi5-cross-linux.ini
# @author Hyeonseok Lee <hs89.lee@samsung.com>
# @date   29 September 2026
# @brief  Cross compilation configuration for Raspberry Pi 5 (Cortex-A76, ARMv8.2-A, aarch64 Linux)
##

[binaries]
c = 'aarch64-linux-gnu-gcc'
cpp = 'aarch64-linux-gnu-g++'
ar = 'aarch64-linux-gnu-ar'
strip = 'aarch64-linux-gnu-strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'cortex-a76'
endian = 'little'

[built-in options]
werror = false
c_args = ['-O3', '-fopenmp', '-march=armv8.2-a+fp16+dotprod+i8mm', '-mtune=cortex-a76', '-I/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/include/openblas', '-I/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/include']
cpp_args = ['-O3', '-fopenmp', '-march=armv8.2-a+fp16+dotprod+i8mm', '-mtune=cortex-a76', '-std=c++17', '-I/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/include/openblas', '-I/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/include']
c_link_args = ['-fopenmp', '-L/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu/openblas-pthread', '-L/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-Wl,-rpath-link,/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-lopenblas', '-lgfortran']
cpp_link_args = ['-fopenmp', '-L/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu/openblas-pthread', '-L/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-Wl,-rpath-link,/hdd/workspace/temp/speaker_diarization/nntrainer/tools/sysroot_arm64/usr/lib/aarch64-linux-gnu', '-lopenblas', '-lgfortran']

[project options]
platform = 'none'
arm-arch = 'armv8.2-a'
enable-fp16 = false
enable-app = true
install-app = true
enable-test = false
enable-logging = true
enable-tflite-backbone = false
enable-nnstreamer-backbone = false
enable-tflite-interpreter = false
enable-mmap = true
mmap-read = true
