// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_quick_ai_gemma4_reference.cpp
 * @date   15 June 2026
 * @brief  Differential (cross-validation) tests for the tiny Gemma4 model.
 *
 * Compares nntrainer's Gemma4 output against golden fixtures generated by
 * HuggingFace transformers (generate_gemma4_reference.py). The generic checks
 * live in quick_ai_test_utils; this file only binds the Gemma4 adapter and the
 * fixture name. Gemma4 sanitizes its configs in the Transformer constructor, so
 * a thin subclass supplies that constructor while inheriting all inference
 * methods from CausalLMTestAdapter. Tests skip automatically when fixtures or
 * the nntr_quantize binary are absent.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <quick_ai_test_utils.h>

#include <gtest/gtest.h>

#include <gemma4_causallm.h>

#include <memory>

namespace {

/**
 * @brief Gemma4 adapter that sanitizes configs before Transformer init
 */
class ReferenceGemma4 final
  : public quick_ai_test::CausalLMTestAdapter<quick_ai::Gemma4CausalLM> {
public:
  ReferenceGemma4(quick_ai::json &cfg, quick_ai::json &generation_cfg,
                  quick_ai::json &nntr_cfg) :
    quick_ai::Transformer(quick_ai::Gemma4Transformer::sanitizeConfig(cfg),
                          quick_ai::Gemma4Transformer::sanitizeGenerationConfig(
                            generation_cfg, cfg),
                          nntr_cfg, quick_ai::ModelType::CAUSALLM),
    quick_ai_test::CausalLMTestAdapter<quick_ai::Gemma4CausalLM>(
      cfg, generation_cfg, nntr_cfg) {}
};

/**
 * @brief Differential model descriptor for the tiny Gemma4 fixture
 */
quick_ai_test::DifferentialModel gemma4Model() {
  return {
    "gemma4_tiny",
    [](quick_ai::json &cfg, quick_ai::json &gen_cfg, quick_ai::json &nntr_cfg) {
      return std::make_unique<ReferenceGemma4>(cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the HF reference
 *
 * The fixture weight save order must match nntrainer's weight-load order, and
 * config.json must carry per-attention-type RoPE (rope_parameters: sliding
 * theta=10000, full proportional partial_rotary_factor=0.25); both are produced
 * by generate_gemma4_reference.py. Max abs logit diff ≈ 2e-4.
 */
TEST(Gemma4DifferentialTest, FP32MatchesHFReference) {
  quick_ai_test::runFp32DifferentialChecks(gemma4Model());
}

/**
 * @brief Q4_0 quantized logits stay within tolerance of the FP32 reference
 */
TEST(Gemma4DifferentialTest, Q40CloseToFP32Reference) {
  quick_ai_test::runQ40DifferentialChecks(gemma4Model());
}

} // namespace
