// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_quick_ai_gemma3_reference.cpp
 * @date   15 June 2026
 * @brief  Differential (cross-validation) tests for the tiny Gemma3 model.
 *
 * Compares nntrainer's Gemma3 output against golden fixtures generated by
 * HuggingFace transformers (generate_gemma3_reference.py). The generic checks
 * live in quick_ai_test_utils; this file only binds the Gemma3 adapter and the
 * fixture name. Gemma3 sanitizes its configs in the Transformer constructor, so
 * a thin subclass supplies that constructor while inheriting all inference
 * methods from CausalLMTestAdapter. Tests skip automatically when fixtures or
 * the nntr_quantize binary are absent.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <quick_ai_test_utils.h>

#include <gtest/gtest.h>

#include <gemma3_causallm.h>

#include <memory>

namespace {

/**
 * @brief Gemma3 adapter that sanitizes configs before Transformer init
 */
class ReferenceGemma3 final
  : public quick_ai_test::CausalLMTestAdapter<quick_ai::Gemma3CausalLM> {
public:
  ReferenceGemma3(quick_ai::json &cfg, quick_ai::json &generation_cfg,
                  quick_ai::json &nntr_cfg) :
    quick_ai::Transformer(sanitizeConfig(cfg),
                          sanitizeGenerationConfig(generation_cfg, cfg),
                          nntr_cfg, quick_ai::ModelType::CAUSALLM),
    quick_ai_test::CausalLMTestAdapter<quick_ai::Gemma3CausalLM>(
      cfg, generation_cfg, nntr_cfg) {}
};

/**
 * @brief Differential model descriptor for the tiny Gemma3 fixture
 */
quick_ai_test::DifferentialModel gemma3Model() {
  return {
    "gemma3_tiny",
    [](quick_ai::json &cfg, quick_ai::json &gen_cfg, quick_ai::json &nntr_cfg) {
      return std::make_unique<ReferenceGemma3>(cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the HF reference
 */
TEST(Gemma3DifferentialTest, FP32MatchesHFReference) {
  quick_ai_test::runFp32DifferentialChecks(gemma3Model());
}

/**
 * @brief Q4_0 quantized logits stay within tolerance of the FP32 reference
 */
TEST(Gemma3DifferentialTest, Q40CloseToFP32Reference) {
  quick_ai_test::runQ40DifferentialChecks(gemma3Model());
}

} // namespace
